### ISSUE TITLE
Issue links don't work

### ISSUE THREAD

**Issue by michaelrsweet** [istopwg/website#1]
Smith Kennedy reported the following on the IPP WG list:

" I was going to fix the document just now, but when I click on the link for http://www.pwg.org/issues/31 the website refuses to take me to the issue.  Same problem if I try to search for issue #31 (http://www.pwg.org/dynamo/issues.php/31?L+P-1+S-2+E0+I30+Z0+Q) - if I click on the 31 it takes me to the PWG homepage.

**Comment by michaelrsweet** [comment]
[master 1ba17b2] Fix issue redirections (Issue #1)

**Comment by wifiprintguy** [comment]
Sorry to be the bearer of bad tidings, but clicking on one of the above links still doesn't take me to the PWG issue 31. 😞 Tested with Safari and Seamonkey - neither work.  Researching this with curl on the command line:

Neuromancer: ~ [510]$ curlproxy -ILk http://www.pwg.org/issues/31
HTTP/1.1 302 Found
Date: Tue, 31 May 2016 17:56:48 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/5.4.16 mod_perl/2.0.9dev Perl/v5.16.3
Location: http://www.pwg.org/dynamo/issues.php?L31
Content-Type: text/html; charset=iso-8859-1
Proxy-Connection: Keep-Alive
Connection: Keep-Alive

HTTP/1.1 302 Found
Date: Tue, 31 May 2016 17:56:48 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/5.4.16 mod_perl/2.0.9dev Perl/v5.16.3
X-Powered-By: PHP/5.4.16
Location: https://www.pwg.org/dynamo/login.php?PAGE=issues.php%3FU31%2BP-1%2BS-2%2BI0%2BE0%2BZ0%2BQ
Content-Type: text/html; charset=UTF-8
Proxy-Connection: Keep-Alive
Connection: Keep-Alive

HTTP/1.1 200 Connection established

<<get into the authentication phase, which I haven't time to figure out with curl>>

Even after I've logged in to the website and then opened the URL, it still doesn't bring up the issue page for 31

**Comment by michaelrsweet** [comment]
There's an issue with the login redirection to the https site not working, which is a separate problem.

Try:

```
https://www.pwg.org/issues/31
```

I'll see what's up with the HTTPS redirection...

**Comment by wifiprintguy** [comment]
OK, that worked.  Now I see why this was closed.  Re-closing.

**Comment by michaelrsweet** [comment]
OK, the issues page was redirecting ?Lnn to ?Unn, but not including dynamo in the path. Fixed.
