### ISSUE TITLE
When "Please correct the highlighted fields" is shown, no fields are highlighted

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/website#2]
If I fill out an issue form, for instance when updating an issue, if I haven't entered all required information I see "Please correct the highlighted fields".  However, no fields are highlighted.

System: OS X 10.11.4, Safari Version 9.1 (11601.5.17.1)

**Comment by wifiprintguy** [comment]
![screen shot 2016-05-12 at 1 59 58 pm](https://cloud.githubusercontent.com/assets/8714934/15228569/05d0ea18-184a-11e6-839c-0b7dc87b3986.png)

**Comment by michaelrsweet** [comment]
Hmm, I just tried it creating a new issue and not filling in any of the information and the summary field is highlighted, just not the others...  Investigating...

**Comment by michaelrsweet** [comment]
Hmm, wasn't passing the "valid" state for all of the input fields.

[master 826fd0a] Fix highlighting of invalid fields (Issue #2)
