### ISSUE TITLE
standards.html: text encoding problem with the 5100.19 description

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/website#24]
See attached - <img width="1057" alt="Screen Shot 2020-02-03 at 9 12 58 PM" src="https://user-images.githubusercontent.com/8714934/73713793-e0150200-46cb-11ea-9210-2e26031f01f9.png">

The problem was observed in both Safari and Firefox (both latest versions as of this reporting date). I'd try to fix the problems but it is on a "dynamo" page and I don't know how that works and don't have bandwidth currently to figure it out.

**Comment by michaelrsweet** [comment]
Not sure what is going on here - the HTML header explicitly sets the character set for the page to UTF-8, and this should be a UTF-8 curly single quote character. I'll edit the database entry for this spec to use a standard quote ("prime") in the abstract...
