### ISSUE TITLE
HTTP request doesn't redirect to HTTPS equivalent

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/website#26]
If I click on this to load the PWG home page (http://www.pwg.org) I now expect it to redirect to its TLS equivalent (https://www.pwg.org). Currently that redirection isn't working, but in the past I thought it was.

**Comment by wifiprintguy** [comment]
Would using VirtualHost or the mod_rewrite as described on this page (https://linuxize.com/post/redirect-http-to-https-in-apache/) do the trick? Which would be better?

A thread on StackOverflow seems to indicate a preference for the VirtualHost method: https://stackoverflow.com/questions/16200501/http-to-https-apache-redirection

**Comment by michaelrsweet** [comment]
So at the moment we only redirect specific pages, but I can update the configuration to redirect all pages.

**Comment by michaelrsweet** [comment]
OK, this is now implemented for all pages.
