### ISSUE TITLE
/ipp/everywhere.html: Links to the IPP Everywhere specification should be updated to v1.1

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/website#29]
Links such as the one found on this line need to be updated to point to the v1.1 specification:

https://github.com/istopwg/website/blob/2d4a2a347ae58a594d40dba40593d87abd8c9123/ipp/everywhere.html#L80

The v1.1 spec is:

http://ftp.pwg.org/pub/pwg/candidates/cs-ippeve11-20200515-5100.14.pdf

**Comment by wifiprintguy** [comment]
Issue resolved but I can't push the document to the website - "553 Access Denied".

@michaelrsweet can you help with this? 😊

**Comment by michaelrsweet** [comment]
@wifiprintguy Try it now...

**Comment by wifiprintguy** [comment]
Successfully pushed to website - thanks @michaelrsweet !
