### ISSUE TITLE
Usage tracking facility for HTTP and FTP offline since server upgrade in early March

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/website#3]
These pages aren't updating since server upgrade in early March:

https://www.pwg.org/usage/
https://www.pwg.org/ftp-usage/

Perhaps the facility that was gathering this information never got updated or re-installed...

**Comment by michaelrsweet** [comment]
OK, at least for the web site we have:

```
https://www.pwg.org/awstats/awstats.pl
```

I need to fix the link on the site menu, and I need to get FTP log analysis working, too.

**Comment by michaelrsweet** [comment]
[master e28a5dd] Update HTTP usage link.
