### ISSUE TITLE
/printers/index.html : Support filtering based on "Family Name"

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/website#30]
The objects in the JSON file contains a "family" field. But typing in the "family" in the filter field yields no results. Extend the Filter field backing code so that text typed into the field will also match objects' family field values.

**Comment by michaelrsweet** [comment]
This change has now been pushed to both the old web site and the new Github site:

[master b32e07e] Add family to search (Issue #30)
[master 88d18db] Sync up changes from pwg.org.
