### ISSUE TITLE
Updated links in "standards.html" file aren't served to users 

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/website#33]
I fixed the links to 5102.1 and 5102.2 in standards.html but the updated links in the file aren't making it to the browser. PHP problem? Tried it in 2 different browsers (Safari and Firefox) and restarted them and problem persists.

**Comment by michaelrsweet** [comment]
"standards.html" is a placeholder for dynamically-generated content. The links need to be fixed in the documents database.

**Comment by wifiprintguy** [comment]
where is the documents database? in the DB on the website itself?

**Comment by wifiprintguy** [comment]
The link for 5102.2 still points here: http://ftp.pwg.org/pub/pwg/candidates/cs-xpcssprt10-20030331-5102.3.html so reopening.

**Comment by michaelrsweet** [comment]
There is a DB table listing documents, and you access it via the user menu on the web site.

I've updated the URL in the table.
