### ISSUE TITLE
"Manage Users" page: Search facility fails to filter / search list of user accounts listings

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/website#4]
On the "Manage Users" page (https://www.pwg.org/dynamo/accounts.php), typing in a string in the "Search Users" text box at the top, and then clicking "Search", I would expect the number of accounts to be filtered to contain only those listings that contained that substring.  But the result list is not filtered.  I tried my name ("Smith"), "HP", and "CSR", and none of them had any effect.

**Comment by michaelrsweet** [comment]
[master 1156058] Fix account search (Issue #4)
