### ISSUE TITLE
Login to the website with no leading "www." in the hostname - password failure

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/website#5]
Generally if one visits "http://pwg.org" there will be a redirect to "http://www.pwg.org".  Bu in some circumstances, the user may arrive at https://pwg.org/dynamo/login.php, and not get redirected, and when that happens their credentials are not accepted.

**Comment by michaelrsweet** [comment]
[master a3ea41c] Login to pwg.org fails (Issue #5)
