### ISSUE TITLE
Website flagged as not secure by Firefox 47.0

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/website#6]
When I try to load the pwg.org login page in Firefox (on either Ubuntu 16.04 or OS X 10.11.5) the page is blocked and the user sees a page like the "Firefox connection is not secure page loading blocked for TLS for www.pwg.org" picture.  ![firefox connection is not secure page loading blocked for tls for www pwg org](https://cloud.githubusercontent.com/assets/8714934/16060583/b42ea8ec-3245-11e6-89f4-5620dfba16d3.png)

If I dig into this, it seems that we are using a certificate authority that doesn't seem to have a CA cert that is distributed with Firefox.  Here is the list of the CAs in Firefox 47.0: 
![firefox 47 0 ca certificate list - no lets encrypt authority x3 ca listed](https://cloud.githubusercontent.com/assets/8714934/16060596/cd6ccabe-3245-11e6-8fd8-d00a300bc0b3.png)

![firefox 47 0 ca list - lets encrypt ca is not there](https://cloud.githubusercontent.com/assets/8714934/16060738/89a9a102-3246-11e6-8fe9-a51a0e874fdf.png)

And here is the Page Info dialog from Firefox, which doesn't provide a "View Certificate" button like Seamonkey does: 
![firefox page info for www pwg org tls page](https://cloud.githubusercontent.com/assets/8714934/16060611/eb151ff8-3245-11e6-8826-b5a7c09f0b34.png)

And here is the Certificate Info page from SeaMonkey, which has it but I don't quite know why / how I got it:

![seamonkey certificate chain info dialog for tls www pwg org page](https://cloud.githubusercontent.com/assets/8714934/16060747/91e04e8e-3246-11e6-8d4f-7ce279be4381.png)

![seamonkey ca list - lets encrypt is there](https://cloud.githubusercontent.com/assets/8714934/16060751/9686a85c-3246-11e6-89bf-5fd8085b23b3.png)

I'm not sure what to do here other than to either choose a different CA or get Firefox to support our CA so that we don't look dodgy.

**Comment by michaelrsweet** [comment]
Sigh... I switched us to "Lets Encrypt" SSL certs when I did the VM upgrade, and Mozilla is one of the major sponsors of that project...

What version of Firefox are you using?

**Comment by wifiprintguy** [comment]
47.0. on my MBP - running OS X 10.11.5.  Something close to that on my Ubuntu 16.04 system, but I don't have it with me right now.

I'll try it on a clean system as well - it is weird that SeaMonkey was fine with it but Firefox is not...I just tried SeaMonkey 2.40 on a PC that I don't use often, and it complained as well about it being an insecure connection.  The CA list in that SeaMonkey on the PC is lacking the Lets Encrypt Authority X3 and Lets Encrypt Authority X1 as well.  I don't recall installing those on my Mac, and they are listed as residing in my "Software Security Device" (the certificate store file used by Mozilla browsers, equivalent to Keychain files).  And looking at the SeaMonkey privacy policy document (http://www.seamonkey-project.org/legal/privacy) I don't see anywhere that they get CA updates so I'm guessing they were installed via an earlier install or that I accepted that CA cert somehow in the course of using the SeaMonkey browser with the website...

**Comment by wifiprintguy** [comment]
What is also interesting is that on my OS X laptop, there is no "Let's Encrypt Authority X3" in the "System Roots" keychain.  But there is a DST Root CA X3, and the "Let's Encrypt Authority X3" is an intermediate for that.  So the OS X / Safari certificate evaluation logic is fine if the root CA is present but the intermediate is not.

The "DST Root CA X3" CA is installed in SeaMonkey and Firefox, but the Mozilla codebase seems to want the direct parent (the intermediate CA) or else it fails the certificate.

**Comment by jhcloos** [comment]
Comparing with a working site secured via lets encrypt, www.pwg.org only
sends its own cert (sn: 0368183bd96e6a75fe97a2e561653afee758), but not
any intermediate certs.

My (working) site also sends the C=US,O=Let's Encrypt,CN=Let's Encrypt
Authority X3 cert (sn: 0a0141420000015385736a0b85eca708) which is signed
by: Issuer: O=Digital Signature Trust Co.,CN=DST Root CA X3.

Adding a SSLCertificateChainFile directive to the apache site config
should fix it.  Mine looks like:

SSLCertificateFile /etc/letsencrypt/live/${HOSTNAME}/cert.pem
SSLCertificateChainFile /etc/letsencrypt/live/${HOSTNAME}/chain.pem

(with the actual hostname of course).

## -JimC

James Cloos cloos@jhcloos.com         OpenPGP: 0x997A9F17ED7DAEA6

**Comment by michaelrsweet** [comment]
Try it now - I was passing the concatenated cert + chain file to Apache (which used to work) but with current Apache (since the upgrade) it stopped working. Added the separate chain file...

**Comment by wifiprintguy** [comment]
Sorry for the delay.  Looks good - no more site security problem notices in Firefox (47.0.1)
