### ISSUE TITLE
Menu item "About -> Mailing Lists" should point to "mailhelp.html", not Mailman main page

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/website#7]
The link in Process 3.0 to the reflectors points here:

http://www.pwg.org/mailhelp.html

But the menus on the website point to the Mailman main page.  Update the menus to point to the mailhelp.html instead (where I added a link to the Mailman main page).

**Comment by michaelrsweet** [comment]
[master ce87839] Use mailhelp.html page for mailing lists (Issue #7)
