### ISSUE TITLE
"IPP Everywhere Self-Certified Printers" page: enable ability for submitter to edit listings

### ISSUE THREAD

**Issue by snappy-pickle** [istopwg/website#8]
In the "IPP Everywhere Self-Certified Printers" page (https://www.pwg.org/dynamo/eveprinters.php) a listing might need to have its model string fixed. Currently site administrators can edit the listings. If lots of requests for these fixes start coming in, they could cause a lot of housekeeping for site administrators.

As such, if it isn't too hard to implement, add the ability to allow the submitter (or perhaps a new role associated with a particular member's organization) to update the listings.

**Comment by michaelrsweet** [comment]
[master 37b10a7] Tweak UI and include of site configuration
