### ISSUE TITLE
"Delete" button for an article doesn't delete the article - shows an error message

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/website#9]
The "delete an article" feature on the PWG website seems to not work.

Steps to reproduce:
1. Go to "http://www.pwg.org"
2. Log in with an account that can manage articles
3. In the "burger" select "Manage Articles"
4. Create a new test article
5. Return to the "manage articles" page (https://www.pwg.org/dynamo/articles.php) once you have created the test article
6. Try to delete it by clicking on the "Delete" button underneath its listing

Expected result:
The article is deleted, with perhaps a "confirmation dialog"

Actual result:
The page shows a message "Bad command 'D'." See attached screen shot.

![screen shot 2017-02-24 at 11 09 19 am](https://cloud.githubusercontent.com/assets/8714934/23315055/bb14e630-fa81-11e6-9a0e-2fbc49a20033.png)

**Comment by michaelrsweet** [comment]
OK, fix checked in - the code was there to do the delete, but the link-up in the page wasn't...
